### ISSUE TITLE
Default cameraconfig for Realsense missing master camera field

### ISSUE THREAD

**Issue by troeggla** [cwi-dis/cwipc#126]
The default `cameraconfig.json` for Realsense cameras is missing a field for defining the master camera.

**Comment by jackjansen** [comment]
This isn't as serious as I thought it was.

The current realsense implementation does a sort of "auto master": if the cameras support sync it will pick a random camera to be the master and the rest to be slaves. That should work perfectly fine, given the bus-architecture of the realsense sync solution.

But we do need to look at sync, because we may want to use another value for slaves (currently we apparently only sync the D camera, not the RGB camera), and we may also want to experiment with genlock-basd syncing (which should be supported nowadays).

**Comment by jackjansen** [comment]
Fixed.
