### ISSUE TITLE
Investigate Android implementation

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc#24]
We should investigate whether an Android implementation is possible (at least for `cwipc_util`, `cwipc_codec` is optional, the current capturers are uninteresting).

**Comment by nachoreimat** [comment]
I think the main interest is `cwipc_codec` cause that will allow us to send compress pointclouds

**Comment by troeggla** [comment]
So I managed to cross-compile PCL for Android (`arm64`). I think that's a big step in the right direction. What other crucial dependencies does CWIPC have?

**Comment by jackjansen** [comment]
The only one that is important is turbo-jpeg. It can probably be worked-around if need be but the codec code uses the turbo-jpeg API, not the normal libjpeg API (which turbojpeg also provides), so it would be better if turbo-jpeg is available.

Can you create a branch (for example `issue24-android`) and check in any projects and such that you've created into the `sandbox` directory? That way I can also have a look at them (but we still keep the main repo structure clean).

**Comment by troeggla** [comment]
Update: I've managed to set up a pipeline to build PCL fairly reliably for armv7, armv8, x86 and x86_64 using a modern version of the build tools used in bashbug/pcl-for-android on Linux (it works on macOS as well, except for the armv8 build, which fails to compile some assembly in boost for some reason; I may have found the issue, but not quite sure yet).

The only real issue is that I can only build PCL statically, dynamic builds fail because it cannot resolve some symbols in `boost::filesystem`. Though this may not really be a problem since I am able to build a dynamic library that links against the static PCL when building an Android app in Android Studio. So my hope is that when I start compiling CWIPC I can built a dynamic library that simply links against the static PCL built. We'll see how that works out.

**Comment by troeggla** [comment]
I can build now shared libraries for ARMv7, ARMv8 and x86_64. This line, however, makes the build fail for x86: https://github.com/cwi-dis/cwipc_util/blob/master/include/cwipc_util/api.h#L62

Not sure how important this is. I can either patch it out it leave it at the architectures we can build now (the x86 builds are for emulators only anyway).

**Comment by jackjansen** [comment]
That is a strange problem: the `struct cwipc_cwipcdump_header` has been carefully laid out to have a certain binary representation, and apparently this fails for the x68_64 Android emulator?

Most practical is to not build for the emulator.

**Comment by troeggla** [comment]
Shared libraries for Android can now be built reliably. The necessary code and documentation has been moved to [cwi-dis/cwipc_android](https://github.com/cwi-dis/cwipc_android). The repository also contains downloadable builds for CWIPC 7.4.3.
