### ISSUE TITLE
Check cwipc-sxr workflow and dataset for cameraconfig.json

### ISSUE THREAD

**Issue by cwidisgroup** [cwi-dis/cwipc#47]
Once #41 has been merged, we need to check the scripts in cwipc-sxr: they may need fixing to produce/consume `cameraconfig.json` in stead of `cameraconfig.xml` files.

We should also check that the current cwipc-sxr data can be used by the new cwipc (so by using the old `cameraconfig.xml` files in the dataset).

Then we should probably release a new micro-release of the dataset, with the XML files replaced by JSON files. But we need to think of how we do this: we don't want to duplicate the complete 1.5TB of data. Ideally we do this in a way that the dataset is both compatible with cwipc `7.4.x` and cwipc `7.5` (and hopefully cwipc `8.x` once we completely get rid of XML file support).

**Comment by jackjansen** [comment]
We need to create a new release for `cwipc-sxr` first, because the command lines (as mentioned in the `sequenceInfo.txt` files in each directory) have changed.

At the very least we need to change the sequenceInfo.txt files to have instructions for cwipc v7.4 and v7.5.

But if we're at it we might as well also create the correct `cameraconfig.json` files by converting the XML files to JSON. And while we're at it add some information to each README file about viewing the `raw` files, and also pointing to the `sequenceInfo.txt` files for more information.

The resulting new release of cwipc-sxr can be a micro-release, because the actual bits of the data should not change.

**Comment by jackjansen** [comment]
The work is done.
