### ISSUE TITLE
Windows: cwipc_kinect does not load

### ISSUE THREAD

**Issue by thong-nt** [cwi-dis/cwipc#68]
Hi,

I tried to install the software (latest version), But it encounters this error: FileNotFoundError: Could not find module 'cwipc_kinect.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Following your instruction and all Path have been added to the system environment, I installed using both exe file and build from source but still have the same issue. However, I rolled back to the 7.3.7+7.3.7 version. It worked well.

Can you please have a look at this issue? It would be nice to work with the latest version. 

P/s: I created a python script just to read the cwipc_kinect.dll file. Despite the file exists, the error still happened, I assumed that the dependencies are somehow missing.

Hope to hear from you soon.
Thong

**Comment by jackjansen** [comment]
These issues are _very_ difficult to debug, because Windows does not give enough information in the error messages when it fails to load a DLL.

cc @troeggla because we need to document the procedure I'm explaining in this message (or, better, create a better way to debug these problems).

I have changed the title of this bug report to what I _think_ you are reporting. Please change back if I am misunderstanding.

There are a few things you can try:

1. Ensure your problem is _only_ with the Kinect support in cwipc. Ensure that `cwipc_view --synthetic` opens a window showing you a synthetic pointcloud. If this works it means that `cwipc_util` and its dependencies are working correctly, and that the Python interfaces to cwipc are also working.
2. Download Dependencies from https://github.com/lucasg/Dependencies This is a very useful tool to help analyse DLL loading problems. Run `DependenciesGui.exe` and drop the `cwipc_kinect.dll` on it. Check the bottom section (and maybe also the top-left section) for any DLLs referenced that are not found. If anything is missing: try to determine which package it should have been loaded from, and double-check that:
  - this package has been installed
  - it is the correct version (i.e. the version that cwipc expects)
  - the directory that the dll is in is on the `PATH` environment variable (Control Panel->System Properties->Environment Variables->System Variables->PATH)
3. If everything seems fine in `Dependencies` there is a last thing you can do. Visual Studio can print very detailed information about loading of DLLs. Do the following:
  - In a command prompt run `cwipc_view --kinect --pausefordebug`
  - It will print its process id. Open Visual Studio, continue without code, Debug->Attach to Process, select the Python process with this process id, attach.
  - Look at the "Output" debug window (probably one of the tabs in the lower right. It should already have a lot of `Python.exe (Win32): loaded xxxxxx.dll` messages,
  - Goto the "Breakpoints" window, New->Function Breakpoint, Function Name `ExitProcess`, OK.
  - Goto your terminal window, type Y and return.
  - Presumably that will now show the FileNotFound for cwipc_kinect.dll. Go to the Visual Studio output window. It should have a `Loaded` message for `cwipc_kinect`, followed by a `Loaded` message for various other things, followed by a lot of `Unloaded` messages (including for `cwipc_kinect`).
  - Compare the list of DLLs that were loaded with the list that you got from `Dependencies`. Hopefully you can spot which DLL is causing problems.

**Comment by jackjansen** [comment]
@thong-nt we have created a new helper program that we hope helps you with debugging this.

Please get the latest HEAD of the cwipc repository master branch and build and install it.

After installation, there is a command line program `cwipc_check` that will check whether everything has been installed correctly. If that isn't the case (in other words, if something hasn't been installed correctly) the script should tell you what to do to fix things.

There is a chance that "what to do to fix things" is currently incomplete, and won't work for you, but then we can work together on making it do the right thing.

**Comment by thong-nt** [comment]
Hi, 

Thank you for the update. I will work on that and come back later.

Also, I don't know if this information is useful for you or not, but just to let you know. I tried to build from source - 7.3.7+7.3.7 version. The error also happened: Could not find module 'cwipc_kinect.dll' (or one of its dependencies). I looked at the size of cwipc_kinect.dll is 176MB (Build from source), while the size of it in installation folder (using the provided .exe) is 174MB.
Then I tested with copying the 174MB file into the build from source, It worked perfectly. So It could be the problem of cmake when generating the files? Note that I added everything to system enviroment based on the instruction.

**Comment by jackjansen** [comment]
@thong-nt Could you please check whether this issue still exists, if you use the `nightly build` installer and/or build from source?

**Comment by thong-nt** [comment]
> @thong-nt Could you please check whether this issue still exists, if you use the `nightly build` installer and/or build from source?

Hi, I installed the latest version successfully in a new machine (Reinstalled Windows) and it works perfectly. It both works when I use the nightly build installer and/or build from source. 

So, I guess maybe the dependency is messed up when upgrade from old version.
